#---------------------------------------------------------
# - Setup AWS CLI environment using the secrets from this repo.
# - Try to create the AWS Elastic Container Registry repository
#---------------------------------------------------------
name: Test this action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # required antecedent
      - uses: actions/checkout@v3.5.2

      # required antecedent
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # This action
      - name: Use the action in this repo to create an AWS ECR repository
        uses: ./
        with:
          aws-ecr-repository: openedx_test_repo
